//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stump.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stump.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;RSAKeyValue&gt;&lt;Modulus&gt;ptXHWNIj6BoqXpmzx8cIm+OYYXf+Q7hBEb8qL+OnVJGOW1nDj1AqD/mH6BXzyqJPbpKE4GJu724lvfPTZpcOMc0y0PklxcUlkEAB2uxgoSowYPmGdVbyMMWduLektcWHQKnXARn8ATeMJx0d3967PraTQiXIoH6EDEc8n03V08U=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string _public {
            get {
                return ResourceManager.GetString("_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;RSAKeyValue&gt;&lt;Modulus&gt;ptXHWNIj6BoqXpmzx8cIm+OYYXf+Q7hBEb8qL+OnVJGOW1nDj1AqD/mH6BXzyqJPbpKE4GJu724lvfPTZpcOMc0y0PklxcUlkEAB2uxgoSowYPmGdVbyMMWduLektcWHQKnXARn8ATeMJx0d3967PraTQiXIoH6EDEc8n03V08U=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;1Zu+AZiXlfwi0Vs6B/orVe/j2s9SNtEShS/w3s9A27iiz1KmOAGBA0+0c4o9F5Q9OYDfTFXLxSGvdois1i4h4Q==&lt;/P&gt;&lt;Q&gt;x/G+lyVRFDl1m2rDOODsljNqOo6cgcJFo2ffSdddOop8cDI0oCB1wpwsFmIgqmsQYXOayrmm3P9E1SfmvB02ZQ==&lt;/Q&gt;&lt;DP&gt;uRNy4pEirepDBKAFPMot6AysoHZHJoWphUqPaY2rBXUJY5aZvCbZcFQL5pvc6OQg1ATr9IjVwBy6mXo8PmrEIQ==&lt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string privatepublic {
            get {
                return ResourceManager.GetString("privatepublic", resourceCulture);
            }
        }
    }
}
